### PR TITLE
chore: Upgrade peer dependency ink

### PR DESCRIPTION
**Pull request by jlarmstrongiv**
Closes https://github.com/vadimdemedes/pastel/issues/71

### CODE REVIEW

**Comment by jlarmstrongiv** [comment]
I updated the PR to fix `xo` linting errors from updates to https://github.com/sindresorhus/eslint-plugin-unicorn 👍 triggering another workflow run would be great!

**Comment by sindresorhus** [comment]
CI is failing. Make sure `npm test` succeeds locally.

**Comment by jlarmstrongiv** [comment]
Not sure why, but I was only able to get `ava` to run tests by setting `NODE_OPTIONS` directly https://github.com/avajs/ava/issues/2593

Please try re-running the CI.  While some tests were timing out due to my local environment, I am more confident the CI should pass.

**Comment by sindresorhus** [comment]
Ink 5 requires Node.js 18, so to support that, we also need to require it. Also update the Ink dev dependency so we can be sure it works.

**Comment by jlarmstrongiv** [comment]
Alrighty, I originally thought it may be possible for pastel to support both ink v4 and v5, but I have changed it to require `ink@5` and nodejs `>=18` 👍 tests still seem to pass, but you’ll need to run the workflow to confirm

Last but not least, as the minimum version of node has changed, I bumped pastel a major version to v3

**Comment by sindresorhus** [comment]
> I bumped pastel a major version to v3

Don't make unrelated changes.

**Pull request merged**
