### PR TITLE
Add support for typescript

### PR DESCRIPTION
**Pull request by zimme**
Based on #7 I fiddled around a bit and got typescript working =)

Not sure if we should commit the `package-lock.json` in the typescript test fixture folder or not.

### CODE REVIEW

**Comment by zimme** [comment]
If this is merged and once `create-parcel-app` starts using the version including this, we should update `create-parcel-app` to add a `tsconfig.json` file that contains this.
```
{
  compilerOptions: {
    "jsx": "react"
  }
}
```

**Comment by vadimdemedes** [comment]
Nice work! I will merge it, but then will try to add support for parsing TS types instead of `propTypes` before releasing ;) 

> Not sure if we should commit the package-lock.json in the typescript test fixture folder or not.

Nope, no need for it!

**Comment by chrisdrackett** [comment]
@vadimdemedes any eta on typescript support? Or is it already supported?

**Comment by vadimdemedes** [comment]
I just tested it and it doesn't seem to work unless I'm doing something wrong:

```
$ mkdir pastel-test && cd pastel-test
$ npx create-pastel-app
$ add tsconfig.json from @zimme
$ npm run build
$ pastel-test --name=Jane
The above error occurred in the <Hello> component:
    in Hello
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
ReferenceError: React is not defined
```

**Comment by zimme** [comment]
It was quite a long time ago I worked on this so maybe there's been updates to React that doesn't play well with this or updates to typescript.

I have no answer currently as to what is causing the error and I don't know when I'll have time to look into this either.

**Pull request merged**
